# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: de
title: Anfängerkrebs Podcast
author: Stefan Wintermeyer
email: stefan@wintermeyer.de
subtitle: "Diagnose: Hodgkin Lymphom. Könnte schlimmer sein. Aber auch deutlich besser."
description: >- # this means to ignore newlines until "baseurl:"
  Stefan hat einen Knoten unterm Arm. Nach ein paar Arztbesuchen und einer Biopsie
  steht fest, dass dieser 3 cm große Knoten sein Leben erst mal auf den Kopf
  stellen wird. In diesem Podcast erzählt er, wie es ist, einen Krebs zu haben,
  der potenziell tödlich ist, aber gute Heilungschancen hat. Einen Krebs, dessen
  Schreibweise er sich erst mal schlecht merken kann (Hodgkin Lymphom), aber von dem
  alle Ärzte sagen: "Wenn schon Krebs, dann am liebsten den." Ein Krebs für
  Anfänger also.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.anfaengerkrebs.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wintermeyer
github_username:  wintermeyer

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

sass:
  sass_dir: assets/css/
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _bin
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
  - README.md
  - DEPLOYMENT.md
  - package.json
  - package-lock.json
  - serve.sh
